# Site title and subtitle. This is used in _includes/header.html
title: 'OnePageCRM Developer Portal'

name: 'OnePageCRM Developer'

url: 'http://developer.onepagecrm.com'
rss_path: "/blog"
codeurl: 'http://www.onepagecrm.com'

api_sections: [
    ['doc', 'Documentation'],
    ['tut', 'Tutorial'],
    ['ref', 'Reference'],
    ['dev', 'Developers'],
    ['post', 'Posts'],
    ['intro', 'Introduction'],
    ['basics', 'Basics & Logging In'],
    ['mainresources', 'Main Methods'],
    ['otherresources', 'Beta Methods']
]
markdown: redcarpet
highlighter: rouge
exclude: ['README.md']

baseurl: ''

authors:
  peter:
    name: Peter Armstrong
    display_name: Peter
    #gravatar: c66919cb194f96c696c1da0c47354a6a
    email: peter@onepagecrm.com
    web: http://onepagecrm.com
   # twitter: company
    github: peterOnePageCRM
    description: 'Peter is a developer at OnePageCRM.'
    image: '/img/peter.jpg'
  john:
    name: John Maguire
    display_name: John
    #gravatar: c66919cb194f96c696c1da0c47354a6a
    email: john@onepagecrm.com
    web: http://onepagecrm.com
   # twitter: company
    github: JohnMaguir
    description: 'John is a graduate developer at OnePageCRM.'
    image: '/img/john.jpg'