# Site title and subtitle. This is used in _includes/header.html
title: 'OnePageCRM Developer Portal'

name: 'OnePageCRM'

codeurl: 'http://www.onepagecrm.com'

api_sections: [
    ['doc', 'Documentation'],
    ['tut', 'Tutorial'],
    ['ref', 'Reference'],
    ['dev', 'Developers'],
    ['post', 'Posts'],
    ['intro', 'Introduction'],
    ['basics', 'Basics & Logging In'],
    ['mainresources', 'Main Resources'],
    ['otherresources', 'Other Resources']
]
markdown: redcarpet
pygments: true
exclude: ['README.md']

baseurl: ''

authors:
  peter:
    name: Peter Armstrong
    display_name: Peter
    #gravatar: c66919cb194f96c696c1da0c47354a6a
    email: peter@onepagecrm.com
    web: http://onepagecrm.com
   # twitter: company
    github: peterOnePageCRM
    description: 'Peter is a developer at OnePageCRM. '
    image: '/img/peter.jpg'