# Site title and subtitle. This is used in _includes/header.html

title: ' Developer Workspace'
name: 'Developer Workspace'
url: 'https://developer.onepagecrm.com'
rss_path: "/blog"
codeurl: 'http://www.onepagecrm.com'

api_sections: [
    ['doc', 'Documentation'],
    ['tut', 'Tutorial'],
    ['ref', 'Reference'],
    ['dev', 'Developers'],
    ['post', 'Posts'],
    ['intro', 'Introduction'],
    ['basics', 'Basics & Logging In'],
    ['mainresources', 'Main Methods'],
    ['otherresources', 'Beta Methods']
]
exclude: ['README.md']

baseurl: ''
host: 0.0.0.0
port: 4000

# Build settings
markdown:               kramdown
theme:                  minima

plugins_dir:
  - jekyll-feed
  - jekyll-paginate

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from

paginate:               6
permalink:              /:title/