# Site title and subtitle. This is used in _includes/header.html
title: 'OnePageCRM Developer Portal'

name: 'OnePageCRM'

codeurl: 'http://www.onepagecrm.com'

api_sections: [
    ['doc', 'Documentation'],
    ['tut', 'Tutorial'],
    ['ref', 'Reference'],
    ['dev', 'Developers'],
    ['post', 'Posts'],
    ['intro', 'Introduction'],
    ['basics', 'Basics & Logging In'],
    ['mainresources', 'Main Resources'],
    ['otherresources', 'Other Resources']
]
markdown: redcarpet
pygments: true
exclude: ['README.md']

baseurl: ''